### ISSUE TITLE
Current state of Visual Studio support

### ISSUE THREAD

**Issue by xchrdw** [jeremyong/Selene#47]
I already tried to make selene run with Visual Studio about half a year ago and it failed because of some compiler bugs (#22).
I just got a response from MS that they solved this specific problem in Visual Studio 2013 Update 3 and tried it again. (http://connect.microsoft.com/VisualStudio/feedbackdetail/view/826262/cl-exe-crashes-on-extensive-template-use)
MS still doesn't support some features but it seems possible to work without them. (no constexpr, rvalue refs, ...). Two tests fail, one with an error in lua (calling null) the other when comparing the returned tuple of a multireturn function call with the expected result. I didn't further look into them.
https://github.com/xchrdw/Selene/compare/vs2013_3

After this I tried the same with Visual Studio 2014 CTP and it looks like Microsoft finally implemented the most important things. Only initializer lists in constructors are missing and all tests succeed :)
https://github.com/xchrdw/Selene/compare/vs2014_ctp

I can just leave these branches here or create a PR for the VS2014 branch if you're interested in it.

**Comment by deathicon** [comment]
When I try the vs2013_3 patch, it crashes automatically when chaining operator[]. Any chance vs2013_3 will ever be supported?

**Comment by Bulat-Ziganshin** [comment]
I should write here since VS2013 branch doesn't allow Issues. xchrdw, look at http://stackoverflow.com/questions/662084/whats-the-difference-between-the-win32-and-win32-defines-in-c

my first attempt to include your selene.h failed, now i changed it to _WIN32 and it works. Of course, it will be even better to check compiler version; or may be do it unconditionally

i wonder what are advantages of constexpr over const here, may be it should be sacrificed for the VS2013 support? 3 best Lua/C++ binding libraries i've found, doesn't work with VS2013, so i tried xchrdw fork as the best possible alternative

**Comment by Querijn** [comment]
http://www.microsoft.com/en-us/download/confirmation.aspx?id=41151

33 MB installer, follow the install instructions and it works fine. Having some trouble with _lua_rotate not being found?

**Comment by jeremyong** [comment]
I believe issues with constexpr and ref qualifiers should be resolved now. In addition, I believe MSVC2015 has full support for the features
