### ISSUE TITLE
How to check if sel::Selector is a table and get its length? 

### ISSUE THREAD

**Issue by ale-carra** [jeremyong/Selene#75]
I have this lua table:

```lua
clips = {{x=80, y=0, w=79, h=79}, --aiming up
	{x=0, y=79, w=79, h=55}, --standing legs
	{x=80, y=79, w=79, h=55}, --running (legs)
	{x=160, y=79, w=79, h=55}, --running 2
	{x=240, y=79, w=79, h=55}, --running 3
	{x=320; y=79, w=79, h=55}, --running 4
	{x=400, y=79, w=79, h=55}, --jumping (legs)
	{x=480, y=79, w=79, h=55}, --jumping 2
	{x=560, y=79, w=79, h=55}, --jumping 3
	{x=0, y=138, w=79, h=55},--jumping 4
	{x=0, y=197, w=79, h=139}--crouch
}
```

And I want to access it from c++. How do I get the amount of elements in sel::State state["clips"] so I can get all the nested tables without knowing the length of the array beforehand? Sorry for asking this here but I couldn't find anywhere else to ask.

**Comment by jeremyong** [comment]
An easy way might be to add a size function to the clips table and just invoke that.
```
int size = state["clips"]["get_size"]();
// etc
```

**Comment by ale-carra** [comment]
I have another issue, this time it's with reading a string. I have this in the lua script:
```lua
name = "alex"
```

But for some reason when doing this in C++, name ends up being NULL instead of "alex":
```C++
sel::State state{true};
char* name = state["name"];
```
Is there anything I did wrong?

**Comment by jeremyong** [comment]
You are trying to store something in the Lua runtime to a `char*` which has a `sizeof` a pointer. That can't work because the string needs to be heap allocated. Use `std::string name` instead. I suggest looking at https://github.com/jeremyong/Selene/blob/master/test/interop_tests.h for examples of usage. Hopefully the different test cases will be descriptive enough.
